name: CI/CD Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: docker compose up -d --build --wait
        - if: failure()
          run: |
           mysql --protocol=tcp -h localhost -uroot -pahmadzia -e "CREATE DATABASE university;
           docker compose up
           docker compose logs cd-backend-1
           curl -I http://localhost/ || true
           curl -I http://localhost/api/items/ || true
